FROM alpine:latest

RUN apk add --no-cache net-snmp-tools python3 py3-pip

COPY ./daria/config/snmptrapd/snmptrapd.conf /etc/snmptrapd.conf
COPY ./daria/scripts/trap_handler.py /handler.py

RUN pip3 install aiohttp

CMD ["sh", "-c", "snmptrapd -Lf /dev/stdout -n -m ALL -O n -c /etc/snmptrapd.conf | python3 /handler.py"]