FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    ansible \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

RUN ansible-galaxy collection install community.network

WORKDIR /app

RUN pip install --no-cache-dir redis pyyaml

COPY worker.py .

CMD ["python", "worker.py"]